# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call('_blabla_rcppeigen_hello_world', PACKAGE = 'blabla')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_blabla_rcppeigen_outerproduct', PACKAGE = 'blabla', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_blabla_rcppeigen_innerproduct', PACKAGE = 'blabla', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_blabla_rcppeigen_bothproducts', PACKAGE = 'blabla', x)
}

functest1 <- function(x) {
    .Call('_blabla_functest1', PACKAGE = 'blabla', x)
}

functest2 <- function(x, i) {
    .Call('_blabla_functest2', PACKAGE = 'blabla', x, i)
}

autos <- function(x) {
    .Call('_blabla_autos', PACKAGE = 'blabla', x)
}

